---
tags: []
layout: input_right
editor: code
type: problem
extra_visible: false
language: 
teacher_info: La idea es volver a hacer este ejercicio (ya apareció en la primera
  práctica), pero con recursividad
manual_evaluation: false
